### Testing valid MCSD request

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "properties": {
        "subject_organization_id": "00000666",
        "client_qualifications": ["mcsd_update"]
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Organization/_history"
    },
    "context": {
      "data_holder_organization_id": "00000659"
    }
  }
}

### Testing search type request with valid parameter

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "properties": {
        "subject_organization_id": "00000666",
        "client_qualifications": ["mcsd_update"]
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Organization?",
      "query_params": {
        "_since": ["foo"]
      }
    },
    "context": {
      "data_holder_organization_id": "00000659"
    }
  }
}

### Testing request that leads to the "gesloten vraag"

POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "properties": {
        "subject_id": "000095254",
        "subject_role": "01.015",
        "subject_organization_id": "00000666",
        "subject_facility_type": "Z3",
        "client_qualifications": ["bgz_professional"]
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Patient?"
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "data_holder_facility_type": "Z3"
    }
  }
}

### Testing request that parses a patient id
POST http://localhost:8081/pdp/v1/data/knooppunt/authz
Content-Type: application/json

{
  "input": {
    "subject": {
      "properties": {
        "subject_id": "000095254",
        "subject_role": "01.015",
        "subject_organization_id": "00000666",
        "subject_facility_type": "Z3",
        "client_qualifications": ["bgz_professional"]
      }
    },
    "request": {
      "method": "GET",
      "protocol": "HTTP/1.0",
      "path": "/Patient/3E439979-017F-40AA-594D-EBCF880FFD97"
    },
    "context": {
      "data_holder_organization_id": "00000659",
      "data_holder_facility_type": "Z3"
    }
  }
}
